# Generated by Django 3.2.1 on 2021-05-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
                ('img_url', models.TextField(default=None)),
            ],
        ),
    ]
