# Generated by Django 3.2.1 on 2021-05-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
                ('email', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
