# Generated by Django 3.2.1 on 2021-05-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
